name: Release

on:
  push:
    tags:
      - "*"

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Get the version
      id: version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\/v/}
      shell: bash
    - name: Echo
      run: echo ${{ steps.version.outputs.VERSION }}
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore JPPhotoManager/JPPhotoManager.sln
    - name: Build
      run: dotnet build --no-restore --configuration Release -p:Version="${{ steps.version.outputs.VERSION }}" JPPhotoManager/JPPhotoManager.sln
    - name: Test
      run: dotnet test --no-build --configuration Release --verbosity normal JPPhotoManager/JPPhotoManager.Tests/JPPhotoManager.Tests.csproj
    - name: Publish
      run: dotnet publish --no-build --configuration Release -p:PublishSingleFile=false JPPhotoManager/JPPhotoManager.UI/JPPhotoManager.UI.csproj
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        filename: 'publish.zip'
        path: .
        directory: JPPhotoManager/JPPhotoManager.UI/bin/Release/net5.0-windows/publish
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.RELEASE_TOKEN }}"
        prerelease: false
        files: |
          LICENSE
          JPPhotoManager/JPPhotoManager.UI/bin/Release/net5.0-windows/publish/*.zip
